### ISSUE TITLE
Misleading Error-Message when trying to connect to a Sonar-Server

### ISSUE THREAD

**Issue by ze-german** [TeklaCorp/VSSonarQubeExtension#177]
When I try to connect to my Sonar-Server (where the webUI is reached under http://foo.bar )without specifying the http in the connection the PluginUI returns a "wrong credentials error", while the sonar-runner correctly tells me, that there was no protocoll specified

**Comment by jmecosta** [comment]
Ok, thanks for the report. Try to handle as soon as possible
